import Foundation
import SwiftData

/// Hard Knocks-style narrative event surfaced during camp. Generated by
/// `HardKnocksNarrator` and consumed by `HardKnocksToast` UI.
@Model
final class HardKnocksEvent {
    var id: UUID
    var seasonYear: Int
    /// Raw value of `HardKnocksEventType`.
    var typeRaw: String
    /// Optional player focus (nil for team-wide depth-chart events).
    var playerID: UUID?
    var headline: String
    var body: String
    var occurredAt: Date

    init(
        id: UUID = UUID(),
        seasonYear: Int,
        typeRaw: String,
        playerID: UUID? = nil,
        headline: String,
        body: String,
        occurredAt: Date = .now
    ) {
        self.id = id
        self.seasonYear = seasonYear
        self.typeRaw = typeRaw
        self.playerID = playerID
        self.headline = headline
        self.body = body
        self.occurredAt = occurredAt
    }

    var type: HardKnocksEventType {
        get { HardKnocksEventType(rawValue: typeRaw) ?? .rookieBreakout }
        set { typeRaw = newValue.rawValue }
    }
}
