import SwiftUI
import SwiftData

/// The War Room's **Draft Order** surface, over two horizons (#164).
///
/// The `Next Yr` entry used to be a sixth item in the hub's Tools menu holding
/// exactly one screen: an early look at next year's class. That is not a tool,
/// it is the *other year* of the question this surface already answers — what am
/// I holding, and who is coming — so it folded in here as a horizon segment
/// rather than keeping a permanent slot in the navigation for one list.
///
/// `THIS YEAR` is the draft the club is prepping for: the full pick order, round
/// by round, with the club's own picks called out. `NEXT YEAR` is the draft after
/// it: the picks the club already holds for it (future-year `DraftPick` rows
/// exist at all times, and trades move them), and above those the early look at
/// the class those picks will be spent on.
struct DraftOrderView: View {
    let career: Career
    /// Next year's class, generated by the hub. Empty is fine — the NEXT YEAR
    /// horizon then shows the picks alone.
    var nextYearProspects: [ScoutingEngine.NextYearProspect] = []

    /// Which draft the surface is showing.
    enum Horizon: String, CaseIterable, Identifiable {
        case thisYear, nextYear
        var id: String { rawValue }
        var label: String {
            switch self {
            case .thisYear: return "THIS YEAR"
            case .nextYear: return "NEXT YEAR"
            }
        }
    }

    @Environment(\.modelContext) private var modelContext
    /// Every pick row this career owns, across all draft years. `draftPicks` is
    /// the one year the horizon has selected.
    @State private var allPicks: [DraftPick] = []
    @State private var draftPicks: [DraftPick] = []
    @State private var horizon: Horizon = .thisYear
    /// Draft year the list is showing — the current season whenever it has rows,
    /// otherwise the nearest year that does (see `loadData`).
    @State private var displayedSeason: Int = 0
    /// The two years the segment switches between, resolved from the rows that
    /// actually exist so the segment never offers an empty year it invented.
    @State private var thisYearSeason: Int = 0
    @State private var nextYearSeason: Int = 0
    @State private var teams: [Team] = []
    @State private var expandedRounds: Set<Int> = [1]
    @State private var isLoading: Bool = true

    // MARK: - Performance caches
    @State private var cachedPicksByRound: [(round: Int, picks: [DraftPick])] = []
    @State private var cachedTeamLookup: [UUID: Team] = [:]
    @State private var cachedAbbreviationLookup: [UUID: String] = [:]
    @State private var cachedUserPickNumbers: Set<Int> = []
    @State private var cachedUserTotalPicks: Int = 0
    @State private var cachedUserPickRounds: [Int] = []

    private var userTeamID: UUID? { career.teamID }

    private var teamLookup: [UUID: Team] { cachedTeamLookup }

    private var abbreviationLookup: [UUID: String] { cachedAbbreviationLookup }

    /// Group draft picks by round.
    private var picksByRound: [(round: Int, picks: [DraftPick])] { cachedPicksByRound }

    /// User's pick numbers for highlighting.
    private var userPickNumbers: Set<Int> { cachedUserPickNumbers }

    /// Total picks the user has.
    private var userTotalPicks: Int { cachedUserTotalPicks }

    /// Sorted unique round numbers where the user has picks (incomplete only).
    private var userPickRounds: [Int] { cachedUserPickRounds }

    private func refreshCaches() {
        cachedTeamLookup = Dictionary(uniqueKeysWithValues: teams.map { ($0.id, $0) })
        cachedAbbreviationLookup = Dictionary(uniqueKeysWithValues: teams.map { ($0.id, $0.abbreviation) })
        let grouped = Dictionary(grouping: draftPicks) { $0.round }
        cachedPicksByRound = grouped.keys.sorted().compactMap { round in
            guard let picks = grouped[round] else { return nil }
            return (round: round, picks: picks.sorted { $0.pickNumber < $1.pickNumber })
        }
        cachedUserPickNumbers = Set(draftPicks.filter { $0.currentTeamID == userTeamID }.map { $0.pickNumber })
        cachedUserTotalPicks = draftPicks.filter { $0.currentTeamID == userTeamID && !$0.isComplete }.count
        let userRounds = Set(draftPicks.filter { $0.currentTeamID == userTeamID && !$0.isComplete }.map { $0.round })
        cachedUserPickRounds = userRounds.sorted()
        // Auto-expand rounds where the user has picks so they're visible immediately.
        if !userRounds.isEmpty {
            expandedRounds.formUnion(userRounds)
        }
    }

    var body: some View {
        ZStack {
            Color.backgroundPrimary.ignoresSafeArea()

            if isLoading {
                VStack(spacing: 12) {
                    ProgressView()
                        .progressViewStyle(.circular)
                        .scaleEffect(1.5)
                        .tint(Color.accentGold)
                    Text("Loading Draft Order...")
                        .font(.subheadline)
                        .foregroundColor(.secondary)
                }
            } else {
            VStack(spacing: 0) {
                headerBar
                    .padding(.horizontal, 20)
                    .padding(.top, 16)
                    .padding(.bottom, 8)

                horizonSegment
                    .padding(.horizontal, 20)
                    .padding(.bottom, 8)

                // User picks summary
                userPicksSummary
                    .padding(.horizontal, 20)
                    .padding(.bottom, 8)

                Divider().overlay(Color.surfaceBorder)

                if draftPicks.isEmpty && !showsNextYearClass {
                    emptyState
                } else {
                    List {
                        // The early look leads the NEXT YEAR horizon: the picks
                        // underneath it are what the club will spend on this
                        // class, so the class is the context for the picks and
                        // not the other way round.
                        if showsNextYearClass {
                            // ONE YEAR VOCABULARY ON THIS SCREEN (#152). The
                            // header bar names the year through
                            // `DraftYearLabel.classYear(forStamped:)` off the
                            // displayed season, so the section under it has to
                            // be stamped the same way — `currentSeason + 1` was
                            // lifted out of the deleted `NextYearClassPreview`,
                            // where the surrounding chrome named no year at all,
                            // and inside this surface it printed the THIS YEAR
                            // draft's label over the NEXT YEAR list.
                            NextYearClassSection(
                                classYear: DraftYearLabel.classYear(forStamped: nextYearSeason),
                                prospects: nextYearProspects
                            )
                        }
                        ForEach(picksByRound, id: \.round) { roundGroup in
                            Section(isExpanded: Binding(
                                get: { expandedRounds.contains(roundGroup.round) },
                                set: { isExpanded in
                                    if isExpanded {
                                        expandedRounds.insert(roundGroup.round)
                                    } else {
                                        expandedRounds.remove(roundGroup.round)
                                    }
                                }
                            )) {
                                ForEach(roundGroup.picks) { pick in
                                    draftPickRow(pick: pick, in: roundGroup.round)
                                        .listRowBackground(
                                            pick.currentTeamID == userTeamID
                                                ? Color.accentGold.opacity(0.08)
                                                : Color.backgroundSecondary
                                        )
                                        .listRowInsets(EdgeInsets(top: 4, leading: 16, bottom: 4, trailing: 16))
                                }
                            } header: {
                                roundHeader(round: roundGroup.round, pickCount: roundGroup.picks.count)
                            }
                        }
                    }
                    .scrollContentBackground(.hidden)
                    .listStyle(.sidebar)
                }
            }
            } // end else (not loading)
        }
        .task {
            loadData()
            isLoading = false
        }
        .onChange(of: horizon) { _, _ in applyHorizon() }
    }

    // MARK: - Horizon

    /// Whether the early-look class section is drawn. Only on NEXT YEAR, and only
    /// when the preview actually generated rows — an empty header promising a
    /// class and listing nobody is worse than no header.
    private var showsNextYearClass: Bool {
        horizon == .nextYear && !nextYearProspects.isEmpty
    }

    /// The one control that switches the year.
    ///
    /// NOT gold: the active segment is a `backgroundTertiary` fill with primary
    /// ink, because gold on this screen belongs to the hub's War Room tab and its
    /// action bar (P5), and a third gold fill inside a surface is the drift the
    /// principle exists to stop.
    private var horizonSegment: some View {
        HStack(spacing: 0) {
            ForEach(Horizon.allCases) { option in
                let isActive = horizon == option
                Button {
                    withAnimation(.easeInOut(duration: 0.16)) { horizon = option }
                } label: {
                    Text(option.label)
                        .font(DSType.display(11, .heavy))
                        .tracking(0.6)
                        .foregroundStyle(isActive ? Color.textPrimary : Color.textSecondary)
                        .frame(maxWidth: .infinity, minHeight: 44)
                        .background(
                            RoundedRectangle(cornerRadius: DSCornerRadius.inline)
                                .fill(isActive ? Color.backgroundTertiary : Color.clear)
                        )
                        .contentShape(Rectangle())
                }
                .buttonStyle(.plain)
                .accessibilityLabel("\(option.label) draft")
                .accessibilityAddTraits(isActive ? [.isButton, .isSelected] : .isButton)
            }
        }
        .padding(DSSpacing.xxs)
        .background(
            RoundedRectangle(cornerRadius: DSCornerRadius.card)
                .fill(Color.backgroundSecondary)
        )
        .overlay(
            RoundedRectangle(cornerRadius: DSCornerRadius.card)
                .strokeBorder(Color.surfaceBorder, lineWidth: 1)
        )
    }

    // MARK: - Header

    private var headerBar: some View {
        HStack {
            VStack(alignment: .leading, spacing: 4) {
                Text("DRAFT ORDER")
                    .font(.title3.weight(.heavy))
                    .foregroundStyle(Color.textPrimary)

                Text("\(String(DraftYearLabel.classYear(forStamped: displayedSeason == 0 ? career.currentSeason : displayedSeason))) Draft \u{2022} \(draftPicks.count) total picks")
                    .font(.caption)
                    .foregroundStyle(Color.accentGold)
            }

            Spacer()

            VStack(alignment: .trailing, spacing: 2) {
                Text("Your Picks: \(userTotalPicks)")
                    .font(.caption.weight(.bold))
                    .foregroundStyle(Color.accentGold)
                Text(userPicksSubtitle)
                    .font(.caption2)
                    .foregroundStyle(Color.textTertiary)
            }
        }
    }

    /// Subtitle that explains where the user's picks are located, so they know to
    /// expand the right rounds (default state shows only Round 1).
    private var userPicksSubtitle: String {
        guard !userPickRounds.isEmpty else { return "no picks this draft" }
        if userPickRounds.count == 1, let only = userPickRounds.first {
            return "Round \(only)"
        }
        if let first = userPickRounds.first, let last = userPickRounds.last,
           userPickRounds == Array(first...last) {
            return "across rounds \(first)-\(last)"
        }
        return "rounds " + userPickRounds.map(String.init).joined(separator: ", ")
    }

    // MARK: - User Picks Summary

    private var userPicksSummary: some View {
        let userPicks = draftPicks
            .filter { $0.currentTeamID == userTeamID && !$0.isComplete }
            .sorted { $0.pickNumber < $1.pickNumber }

        return ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 8) {
                ForEach(userPicks) { pick in
                    VStack(spacing: 2) {
                        Text("#\(pick.pickNumber)")
                            .font(.system(size: 14, weight: .heavy).monospacedDigit())
                            .foregroundStyle(Color.accentGold)

                        Text("Rd \(pick.round)")
                            .font(.system(size: 9, weight: .semibold))
                            .foregroundStyle(Color.textSecondary)

                        if pick.originalTeamID != pick.currentTeamID,
                           let origAbbr = abbreviationLookup[pick.originalTeamID] {
                            Text("via \(origAbbr)")
                                .font(.system(size: DSType.Size.micro, weight: .bold))
                                .foregroundStyle(Color.accentBlue)
                        }
                    }
                    .frame(width: 52, height: 52)
                    .background(
                        RoundedRectangle(cornerRadius: 8)
                            .fill(Color.backgroundSecondary)
                            .overlay(
                                RoundedRectangle(cornerRadius: 8)
                                    .strokeBorder(Color.accentGold, lineWidth: 2)
                            )
                    )
                }
            }
        }
    }

    // MARK: - Round Header

    private func roundHeader(round: Int, pickCount: Int) -> some View {
        HStack {
            Text(roundName(round).uppercased())
                .font(.caption.weight(.heavy))
                .foregroundStyle(round <= 3 ? Color.accentGold : Color.textSecondary)

            Spacer()

            Text("\(pickCount) picks")
                .font(.caption2.weight(.semibold))
                .foregroundStyle(Color.textTertiary)
        }
    }

    // MARK: - Draft Pick Row

    private func draftPickRow(pick: DraftPick, in round: Int) -> some View {
        let isUserPick = pick.currentTeamID == userTeamID
        let isTraded = pick.originalTeamID != pick.currentTeamID
        let team = teamLookup[pick.currentTeamID]
        let originalTeam = teamLookup[pick.originalTeamID]

        return HStack(spacing: 10) {
            // Pick number with value indicator
            VStack(spacing: 1) {
                Text("\(pick.pickNumber)")
                    .font(.system(size: 16, weight: .heavy).monospacedDigit())
                    .foregroundStyle(isUserPick ? Color.accentGold : Color.textPrimary)

                // Pick value indicator
                pickValueDot(pickNumber: pick.pickNumber)
            }
            .frame(width: 36)

            // Team info
            VStack(alignment: .leading, spacing: 2) {
                HStack(spacing: 6) {
                    Text(team?.abbreviation ?? "???")
                        .font(.system(size: 13, weight: .bold))
                        .foregroundStyle(isUserPick ? Color.accentGold : Color.textPrimary)
                        .frame(width: 38, height: 24)
                        .background(
                            RoundedRectangle(cornerRadius: 5)
                                .fill(Color.backgroundPrimary)
                                .overlay(
                                    RoundedRectangle(cornerRadius: 5)
                                        .strokeBorder(
                                            isUserPick ? Color.accentGold : Color.surfaceBorder,
                                            lineWidth: isUserPick ? 2 : 1
                                        )
                                )
                        )

                    if let team {
                        Text(team.fullName)
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(Color.textPrimary)
                            .lineLimit(1)
                    }

                    if isUserPick {
                        Text("YOUR PICK")
                            .font(.system(size: DSType.Size.micro, weight: .heavy))
                            .foregroundStyle(Color.backgroundPrimary)
                            .padding(.horizontal, 5)
                            .padding(.vertical, 2)
                            .background(Color.accentGold, in: Capsule())
                    }
                }

                HStack(spacing: 8) {
                    // Record
                    if let team {
                        Text(team.record)
                            .font(.caption2.weight(.semibold).monospacedDigit())
                            .foregroundStyle(Color.textSecondary)
                    }

                    // Trade info
                    if isTraded, let origAbbr = originalTeam?.abbreviation, let currentAbbr = team?.abbreviation {
                        HStack(spacing: 3) {
                            Image(systemName: "arrow.left.arrow.right")
                                .font(.system(size: DSType.Size.micro))
                                .foregroundStyle(Color.accentBlue)
                            Text("Originally: \(origAbbr) \u{2192} \(currentAbbr)")
                                .font(.system(size: 9, weight: .semibold))
                                .foregroundStyle(Color.accentBlue)
                        }
                    }

                    // Already picked info
                    if pick.isComplete, let playerName = pick.playerName, let pos = pick.playerPosition {
                        HStack(spacing: 3) {
                            Text(pos)
                                .font(.system(size: DSType.Size.micro, weight: .bold))
                                .foregroundStyle(Color.textPrimary)
                                .padding(.horizontal, 3)
                                .padding(.vertical, 1)
                                .background(Color.backgroundTertiary, in: RoundedRectangle(cornerRadius: 2))
                            Text(playerName)
                                .font(.caption2.weight(.medium))
                                .foregroundStyle(Color.textSecondary)
                        }
                    }
                }
            }

            Spacer()

            // Pick value label — the tier word plus the Jimmy Johnson points the
            // trade market actually charges, so this screen speaks the same
            // language as the war room and the Trade Center (decision §7.1).
            Text("\(pickValueLabel(pickNumber: pick.pickNumber)) · \(PickValueChart.points(forPick: pick.pickNumber))")
                .font(.system(size: 9, weight: .semibold).monospacedDigit())
                .foregroundStyle(pickValueColor(pickNumber: pick.pickNumber))
                .padding(.horizontal, 6)
                .padding(.vertical, 3)
                .background(
                    Capsule().fill(pickValueColor(pickNumber: pick.pickNumber).opacity(0.12))
                )

            // Trade pick button (user's picks only, placeholder)
            if isUserPick && !pick.isComplete {
                Image(systemName: "arrow.left.arrow.right.circle")
                    .font(.body)
                    .foregroundStyle(Color.textTertiary)
            }
        }
        .padding(.vertical, 2)
        .overlay(
            isUserPick
                ? RoundedRectangle(cornerRadius: 6)
                    .strokeBorder(Color.accentGold.opacity(0.4), lineWidth: 1.5)
                    .padding(-4)
                : nil
        )
    }

    // MARK: - Pick Value Helpers

    private func pickValueDot(pickNumber: Int) -> some View {
        HStack(spacing: 1) {
            let dots = pickValueDotCount(pickNumber: pickNumber)
            ForEach(0..<dots, id: \.self) { _ in
                Circle()
                    .fill(pickValueColor(pickNumber: pickNumber))
                    .frame(width: 4, height: 4)
            }
        }
    }

    private func pickValueDotCount(pickNumber: Int) -> Int {
        switch pickNumber {
        case 1...10:  return 4
        case 11...32: return 3
        case 33...64: return 2
        default:      return 1
        }
    }

    private func pickValueLabel(pickNumber: Int) -> String {
        switch pickNumber {
        case 1...5:    return "Elite"
        case 6...10:   return "Premium"
        case 11...32:  return "High"
        case 33...64:  return "Mid"
        case 65...100: return "Avg"
        default:       return "Low"
        }
    }

    private func pickValueColor(pickNumber: Int) -> Color {
        switch pickNumber {
        case 1...10:   return .accentGold
        case 11...32:  return .success
        case 33...64:  return .accentBlue
        case 65...100: return .textSecondary
        default:       return .textTertiary
        }
    }

    // MARK: - Round Name

    private func roundName(_ round: Int) -> String {
        switch round {
        case 1: return "First Round"
        case 2: return "Second Round"
        case 3: return "Third Round"
        case 4: return "Fourth Round"
        case 5: return "Fifth Round"
        case 6: return "Sixth Round"
        case 7: return "Seventh Round"
        default: return "Round \(round)"
        }
    }

    // MARK: - Empty State

    private var emptyState: some View {
        VStack(spacing: 20) {
            Image(systemName: "list.number")
                .font(.system(size: 52))
                .foregroundStyle(Color.textTertiary)

            Text("No Draft Picks Available")
                .font(.title3.weight(.semibold))
                .foregroundStyle(Color.textPrimary)

            Text("Draft picks will be generated when the season begins.")
                .font(.subheadline)
                .foregroundStyle(Color.textSecondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal, 40)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: - Data Loading

    private func loadData() {
        let cid = career.id
        let pickDesc = FetchDescriptor<DraftPick>(
            predicate: #Predicate { $0.careerID == cid },
            sortBy: [SortDescriptor(\.pickNumber)]
        )
        allPicks = (try? modelContext.fetch(pickDesc)) ?? []

        let teamDesc = FetchDescriptor<Team>(predicate: #Predicate { $0.careerID == cid })
        teams = (try? modelContext.fetch(teamDesc)) ?? []

        // Resolve the two horizons from the rows that exist.
        //
        // Scoping to ONE draft year at a time is the point: future-year rows
        // (seasons N+1…N+3) exist at all times, and showing "everything" would
        // stack three projected boards that share pick numbers into one
        // unreadable list. THIS YEAR is the current season when it has rows and
        // the earliest year that does otherwise; NEXT YEAR is the next year that
        // has rows, falling back to `thisYear + 1` so the segment always names a
        // real calendar year even in a save with no future picks at all.
        let currentYear = career.currentSeason
        let years = Set(allPicks.map(\.seasonYear)).sorted()
        thisYearSeason = years.contains(currentYear) ? currentYear : (years.first ?? currentYear)
        nextYearSeason = years.first { $0 > thisYearSeason } ?? (thisYearSeason + 1)

        applyHorizon()
    }

    /// Points the list at the selected year and rebuilds the caches off it.
    private func applyHorizon() {
        displayedSeason = horizon == .thisYear ? thisYearSeason : nextYearSeason
        draftPicks = allPicks.filter { $0.seasonYear == displayedSeason }
        // The auto-expand in `refreshCaches` unions rounds into `expandedRounds`,
        // so a year with picks in round 6 would leave round 6 open on the year
        // that has none. Reset to the default before the union.
        expandedRounds = [1]
        refreshCaches()
    }
}

// MARK: - Next Year's Class

/// The early look at next year's class, as a **section** of the Draft Order
/// list's NEXT YEAR horizon (#164).
///
/// It used to be `NextYearClassPreview`, a whole `List` behind the hub's Tools
/// menu — one screen, permanently occupying a navigation slot, saying "full
/// scouting begins next season". Folded in here it costs no navigation at all
/// and gains its context: these are the men the picks listed underneath will be
/// spent on.
struct NextYearClassSection: View {
    /// The draft year this class belongs to.
    let classYear: Int
    let prospects: [ScoutingEngine.NextYearProspect]

    var body: some View {
        Section {
            HStack(spacing: DSSpacing.xs) {
                Image(systemName: "eye.fill")
                    .foregroundStyle(Color.textSecondary)
                VStack(alignment: .leading, spacing: 2) {
                    Text("Early Look \u{2014} \(String(classYear)) Draft Class")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(Color.textPrimary)
                    Text("Full scouting begins next season")
                        .font(.caption)
                        .foregroundStyle(Color.textTertiary)
                }
            }
            ForEach(Array(prospects.enumerated()), id: \.element.id) { index, prospect in
                nextYearProspectRow(rank: index + 1, prospect: prospect)
            }
        } header: {
            Text("NEXT YEAR'S TOP PROSPECTS")
                .font(.caption2.weight(.heavy))
                .foregroundStyle(Color.textSecondary)
                .textCase(nil)
        }
        .listRowBackground(Color.backgroundSecondary)
    }

    private func nextYearProspectRow(rank: Int, prospect: ScoutingEngine.NextYearProspect) -> some View {
        HStack(spacing: 10) {
            Text("\(rank)")
                .font(.system(size: 14, weight: .heavy).monospacedDigit())
                .foregroundStyle(rank <= 3 ? Color.accentGold : Color.textTertiary)
                .frame(width: 28, alignment: .trailing)

            Text(prospect.position.rawValue)
                .font(.system(size: DSType.Size.caption, weight: .bold))
                .foregroundStyle(Color.textPrimary)
                .frame(width: 32, height: 22)
                .background(positionColor(prospect.position), in: RoundedRectangle(cornerRadius: DSCornerRadius.tight))

            VStack(alignment: .leading, spacing: 2) {
                Text(prospect.fullName)
                    .font(.subheadline.weight(.medium))
                    .foregroundStyle(Color.textPrimary)
                    .lineLimit(1)
                HStack(spacing: 6) {
                    Text(prospect.college)
                        .font(.caption)
                        .foregroundStyle(Color.textSecondary)
                    Text("\u{00B7}")
                        .font(.caption)
                        .foregroundStyle(Color.textTertiary)
                    Text(prospect.classYear)
                        .font(.caption)
                        .foregroundStyle(Color.textTertiary)
                }
            }

            Spacer()

            Text(prospect.projectedGrade)
                .font(.system(size: DSType.Size.caption, weight: .bold))
                .foregroundStyle(projectedGradeColor(prospect.projectedGrade))
                .padding(.horizontal, DSSpacing.xs)
                .padding(.vertical, DSSpacing.xxs)
                .background(
                    RoundedRectangle(cornerRadius: DSCornerRadius.tight)
                        .fill(projectedGradeColor(prospect.projectedGrade).opacity(0.12))
                )
        }
    }

    private func positionColor(_ position: Position) -> Color {
        switch position.side {
        case .offense:      return .accentBlue
        case .defense:      return .danger
        case .specialTeams: return .accentGold
        }
    }

    private func projectedGradeColor(_ grade: String) -> Color {
        switch grade {
        case "Top 10 Pick": return .accentGold
        case "1st Round":   return .success
        default:            return .textSecondary
        }
    }
}
