import Foundation

// MARK: - Career Game Mode (R40)

/// How the career's league is bootstrapped at creation time.
enum CareerGameMode: String, Codable, CaseIterable {
    /// Real 32-team rosters as generated by `LeagueGenerator`.
    case standard = "Standard"
    /// Every player in the league enters a shared pool and all 32 teams
    /// re-draft their rosters from scratch in a snake draft.
    case fantasyDraft = "FantasyDraft"

    var displayName: String {
        switch self {
        case .standard:     return "Standard"
        case .fantasyDraft: return "Fantasy Draft"
        }
    }
}

// MARK: - Career Scenario (R40)

/// Pre-built career starts. A scenario never introduces new systems — it only
/// parametrizes the generated league: the chosen team's roster strength, the
/// owner archetype traits (R31 `OwnerPersonaEngine` derives from them), and
/// the team's draft capital / cap situation.
enum CareerScenario: String, Codable, CaseIterable {
    /// Weakest roster, extra draft picks, patient owner.
    case rebuild = "Rebuild"
    /// Star-studded but aging roster, demanding win-now tycoon owner.
    case winNow = "WinNow"
    /// Good roster buried under a catastrophic cap sheet.
    case capHell = "CapHell"

    var displayName: String {
        switch self {
        case .rebuild: return "Rebuild"
        case .winNow:  return "Win Now"
        case .capHell: return "Cap Hell"
        }
    }

    var icon: String {
        switch self {
        case .rebuild: return "hammer.fill"
        case .winNow:  return "flame.fill"
        case .capHell: return "exclamationmark.triangle.fill"
        }
    }

    var tagline: String {
        switch self {
        case .rebuild: return "Bare cupboard, full war chest"
        case .winNow:  return "The window is closing"
        case .capHell: return "Talented team, toxic books"
        }
    }

    var blurb: String {
        switch self {
        case .rebuild:
            return "Your roster is stripped down, but you inherit extra premium draft picks and a patient owner who believes in the process."
        case .winNow:
            return "An aging, star-heavy roster with its future picks already spent — and a tycoon owner who expects a title right now."
        case .capHell:
            return "The talent is real, but bloated long-term contracts push you over the cap. Creative surgery required."
        }
    }
}

// MARK: - Injury Frequency (R40)

/// League setting controlling how often the weekly quick-sim injury engine
/// rolls injuries. `normal` keeps today's exact `MedicalEngine` rates.
enum InjuryFrequency: String, Codable, CaseIterable {
    case off    = "Off"
    case low    = "Low"
    case normal = "Normal"

    /// Multiplier applied on top of `MedicalEngine.injuryCheck`'s base risk.
    var riskMultiplier: Double {
        switch self {
        case .off:    return 0.0
        case .low:    return 0.5
        case .normal: return 1.0
        }
    }

    var displayName: String { rawValue }

    var blurb: String {
        switch self {
        case .off:    return "No injuries from weekly simulation."
        case .low:    return "Injuries occur at half the normal rate."
        case .normal: return "Realistic NFL injury rates."
        }
    }
}

// MARK: - Career Setup Card (UI selection)

/// The single-choice "how do you want to start" card in career creation.
/// Maps 1:1 onto a `(CareerGameMode, CareerScenario?)` pair — fantasy draft
/// and scenarios are mutually exclusive by design (a scenario shapes an
/// existing roster; a fantasy draft discards all rosters).
enum CareerSetup: String, CaseIterable, Hashable {
    case standard
    case fantasyDraft
    case rebuild
    case winNow
    case capHell

    var mode: CareerGameMode {
        self == .fantasyDraft ? .fantasyDraft : .standard
    }

    var scenario: CareerScenario? {
        switch self {
        case .rebuild: return .rebuild
        case .winNow:  return .winNow
        case .capHell: return .capHell
        case .standard, .fantasyDraft: return nil
        }
    }

    var displayName: String {
        switch self {
        case .standard:     return "Standard"
        case .fantasyDraft: return "Fantasy Draft"
        case .rebuild:      return CareerScenario.rebuild.displayName
        case .winNow:       return CareerScenario.winNow.displayName
        case .capHell:      return CareerScenario.capHell.displayName
        }
    }

    var icon: String {
        switch self {
        case .standard:     return "sportscourt.fill"
        case .fantasyDraft: return "shuffle"
        case .rebuild:      return CareerScenario.rebuild.icon
        case .winNow:       return CareerScenario.winNow.icon
        case .capHell:      return CareerScenario.capHell.icon
        }
    }

    /// Small category badge shown on the card.
    var badge: String {
        scenario == nil ? "MODE" : "SCENARIO"
    }

    var blurb: String {
        switch self {
        case .standard:
            return "Take over a real franchise as-is. The classic Dynasty experience."
        case .fantasyDraft:
            return "Every player enters one big pool and all 32 teams snake-draft new rosters from scratch."
        case .rebuild:      return CareerScenario.rebuild.blurb
        case .winNow:       return CareerScenario.winNow.blurb
        case .capHell:      return CareerScenario.capHell.blurb
        }
    }
}
