import SwiftUI

// MARK: - College Production Tier Display

extension CollegeProspect.CollegeProductionTier {

    /// Localized long form used in detail screens and comparison sheets.
    /// The enum rawValues are storage keys and are never shown directly.
    var displayName: String {
        switch self {
        case .elite:    return String(localized: "Elite")
        case .aboveAvg: return String(localized: "Above Avg")
        case .average:  return String(localized: "Average")
        case .belowAvg: return String(localized: "Below Avg")
        }
    }

    /// 2–3 character label for dense prospect list columns.
    var abbreviation: String {
        switch self {
        case .elite:    return String(localized: "ELI")
        case .aboveAvg: return String(localized: "AA")
        case .average:  return String(localized: "AVG")
        case .belowAvg: return String(localized: "BA")
        }
    }

    /// Letter grade the tier maps onto so production chips share the unified
    /// 5-tier palette used by every other grade in the app.
    private var equivalentLetter: String {
        switch self {
        case .elite:    return "A+"
        case .aboveAvg: return "A"
        case .average:  return "B"
        case .belowAvg: return "C"
        }
    }

    /// Chip tint — routed through `PositionGradeCalculator.gradeColorForLetter`
    /// so it can never drift from the letter-grade palette.
    var chipColor: Color {
        PositionGradeCalculator.gradeColorForLetter(equivalentLetter)
    }

    /// Sort rank, best tier first.
    var sortRank: Int {
        switch self {
        case .elite:    return 0
        case .aboveAvg: return 1
        case .average:  return 2
        case .belowAvg: return 3
        }
    }
}

// MARK: - College Competition Level Display

extension CollegeProspect.CollegeCompetitionLevel {

    /// Localized short label ("P5" / "G5" / "FCS").
    var displayName: String {
        switch self {
        case .powerFive:   return String(localized: "P5")
        case .groupOfFive: return String(localized: "G5")
        case .fcs:         return String(localized: "FCS")
        }
    }

    /// Localized long label for tooltips and detail rows.
    var longName: String {
        switch self {
        case .powerFive:   return String(localized: "Power 5")
        case .groupOfFive: return String(localized: "Group of 5")
        case .fcs:         return String(localized: "FCS")
        }
    }
}

// MARK: - Development Archetype Display

extension CollegeProspect.DevelopmentArchetype {

    var displayName: String {
        switch self {
        case .polished: return String(localized: "Polished")
        case .balanced: return String(localized: "Balanced")
        case .raw:      return String(localized: "Raw")
        }
    }
}

// MARK: - NFL Readiness Bucket

/// Coarse day-one readiness bucket derived from `CollegeProspect.nflReadiness`.
/// Surfaced as a scouting insight line — readiness itself is never shown as a
/// raw number because it is a hidden generator value.
enum ProspectReadinessBucket {
    case proReady
    case developmental
    case project

    init(readiness: Int) {
        switch readiness {
        case 75...:   self = .proReady
        case 45..<75: self = .developmental
        default:      self = .project
        }
    }

    var label: String {
        switch self {
        case .proReady:      return String(localized: "Pro-ready")
        case .developmental: return String(localized: "Developmental")
        case .project:       return String(localized: "Project")
        }
    }

    var detail: String {
        switch self {
        case .proReady:
            return String(localized: "Can contribute from day one")
        case .developmental:
            return String(localized: "Rotational as a rookie, year-2 leap")
        case .project:
            return String(localized: "Needs seasoning before he is trusted")
        }
    }

    var icon: String {
        switch self {
        case .proReady:      return "checkmark.seal.fill"
        case .developmental: return "hourglass"
        case .project:       return "wrench.and.screwdriver.fill"
        }
    }

    var color: Color {
        switch self {
        case .proReady:      return .success
        case .developmental: return .accentBlue
        case .project:       return .warning
        }
    }
}

// MARK: - Production Tier Chip

/// Compact college-production tier chip (`ELI` / `AA` / `AVG` / `BA`).
///
/// Used as the `PROD` column in every prospect list. College production is a
/// real but imperfect signal generated by `DraftClassBuilder`, so it reads as a
/// separate axis from the scout's overall grade.
struct ProductionTierChip: View {
    let tier: CollegeProspect.CollegeProductionTier

    /// Column width the chip is centered in. `nil` sizes to content.
    var width: CGFloat? = 40

    /// Draws the tinted capsule behind the label.
    var showsBackground: Bool = true

    var fontSize: CGFloat = 9

    var body: some View {
        Text(tier.abbreviation)
            .font(.system(size: fontSize, weight: .heavy))
            .foregroundStyle(tier.chipColor)
            .lineLimit(1)
            .minimumScaleFactor(0.7)
            .padding(.horizontal, showsBackground ? 4 : 0)
            .padding(.vertical, showsBackground ? 2 : 0)
            .background {
                if showsBackground {
                    RoundedRectangle(cornerRadius: 3)
                        .fill(tier.chipColor.opacity(0.15))
                }
            }
            .frame(width: width, alignment: .center)
            .accessibilityLabel(Text("College production: \(tier.displayName)"))
    }
}

/// Micro production label for panels that have no room for a column — renders
/// as an inline `PROD ELI` pair under the prospect's name.
struct ProductionMicroLabel: View {
    let tier: CollegeProspect.CollegeProductionTier
    var fontSize: CGFloat = 8

    var body: some View {
        HStack(spacing: 2) {
            Text("PROD")
                .font(.system(size: fontSize, weight: .semibold))
                .foregroundStyle(Color.textTertiary)
            Text(tier.abbreviation)
                .font(.system(size: fontSize, weight: .heavy))
                .foregroundStyle(tier.chipColor)
        }
        .accessibilityElement(children: .ignore)
        .accessibilityLabel(Text("College production: \(tier.displayName)"))
    }
}
